root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
extends:
  - 'standard'
  - 'plugin:@typescript-eslint/recommended'
rules:
  '@typescript-eslint/indent': ['error', 2]
  '@typescript-eslint/member-delimiter-style':
    - 'error'
    - multiline:
        delimiter: 'none'
  '@typescript-eslint/explicit-function-return-type':
    - 'error'
    - allowExpressions: true
      allowTypedFunctionExpressions: true
overrides:
  - files: [ '*.js', '*.mjs' ]
    parser: 'espree'
  - files: [ '*.js' ]
    rules:
      '@typescript-eslint/no-var-requires': 'off'
  - files:
    - '*.test.ts'
    - '*.spec.ts'
    - '*.test.js'
    - '*.spec.js'
    env:
      jest: true
